<a href="https://colab.research.google.com/github/B34R-e/Pytorch-Tutorial/blob/main/Pytorch_Tutorial_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch

# create 0 values tensor

x = torch.empty(2)

print(x)

tensor([-4.1490e-16,  4.5639e-41])


In [12]:
# create random values tensor
x = torch.rand(2, 2, 2)

print(x)

tensor([[[0.0690, 0.5937],
         [0.3497, 0.0884]],

        [[0.6096, 0.7850],
         [0.6927, 0.1776]]])


In [13]:
# check the data type of tensor

print(x.dtype)

torch.float32


In [14]:
# create 1 value tensor

x = torch.ones(2, 2)

print(x)

tensor([[1., 1.],
        [1., 1.]])


In [15]:
# check the size of tensor

x = torch.ones(2, 2, dtype = torch.float16)

print(x.size())

torch.Size([2, 2])


In [16]:
# create tensor from data

x = torch.tensor([2.5, 0.1])

print(x)

tensor([2.5000, 0.1000])


In [22]:
# basic operations

x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(f'X tensor: {x}\n')
print(f'Y tensor: {y}\n')

# addition (element-wise)
z = x + y
z = torch.add(x, y)
y.add_(x) # add the value of x to y
x.add_(y) # add the value of y to x

print(f'Addition: {z}\n')

X tensor: tensor([[0.2124, 0.8965],
        [0.2333, 0.8369]])

Y tensor: tensor([[0.9617, 0.0717],
        [0.6518, 0.6181]])

Addition: tensor([[1.1741, 0.9682],
        [0.8851, 1.4550]])



In [23]:
# Subtraction
z = x - y
z = torch.sub(x, y)

print(f'Subtraction: {z}')

Subtraction: tensor([[-0.7493,  0.8248],
        [-0.4186,  0.2188]])


In [24]:
# Multiplication
z = x * y
z = torch.mul(x, y)

print(f'Multiplication: {z}')

Multiplication: tensor([[0.2043, 0.0643],
        [0.1521, 0.5173]])


In [25]:
# Division
z = x / y
z = torch.div(x, y)

print(f'Division: {z}')

Division: tensor([[ 0.2209, 12.5073],
        [ 0.3579,  1.3540]])


In [28]:
# Index slicing
x = torch.rand(5, 3)

print(x)
print(x[:, 0])
print(x[1, 1].item()) # only can use when you have 1 element

tensor([[0.0427, 0.9436, 0.2034],
        [0.0762, 0.7273, 0.3519],
        [0.4355, 0.3456, 0.4399],
        [0.5344, 0.8043, 0.0257],
        [0.9311, 0.9627, 0.4927]])
tensor([0.0427, 0.0762, 0.4355, 0.5344, 0.9311])
0.7273129820823669


In [35]:
# Reshape a tensor
x = torch.rand(4, 4)
print(x)

# y = x.view(16)
y = x.view(-1, 8)
print(y, '\n')
print(y.size())

tensor([[0.4988, 0.6767, 0.9340, 0.2338],
        [0.2559, 0.0686, 0.3668, 0.6827],
        [0.5193, 0.2459, 0.8827, 0.3413],
        [0.7044, 0.8702, 0.8012, 0.9342]])
tensor([[0.4988, 0.6767, 0.9340, 0.2338, 0.2559, 0.0686, 0.3668, 0.6827],
        [0.5193, 0.2459, 0.8827, 0.3413, 0.7044, 0.8702, 0.8012, 0.9342]]) 

torch.Size([2, 8])


In [40]:
# Torch to numpy (Share the allocation together)
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [43]:
# Numpy to torch (Share the allocation together)

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

b.add_(1)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [45]:
# Check if your cuda tool kit is available
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device = device) # create a tensor and put it in GPU
  y = torch.ones(5)
  y = y.to(device) # just like the x
  z = x + y
  z = z.to('cpu') # turn back to the cpu to perform on numpy

print(z)

tensor([[ 0.2209, 12.5073],
        [ 0.3579,  1.3540]])


In [ ]:
#
x = torch.ones(5, requires_grad = True) # to compute gradient after
print(x)